steps:
  - name: 'gcr.io/buildpacks/builder'
    args: ['build', '-t', 'gcr.io/speedy-bazaar-382611/flask-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/speedy-bazaar-382611/flask-app']
images:
  - 'gcr.io/speedy-bazaar-382611/flask-app'
